apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: guillsav/proshop/products
          env:
            - name: PORT
              value: '8082'
            - name: MOGO_URI
              value: 'mongodb://products-mongo-srv:27017/products'
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 8082
      targetPort: 8082
